import io
import logging
import os
import re
from datetime import datetime, timezone

import markdown
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from google.cloud import logging as gcloud_logging
import google.cloud.firestore as firestore
from pydantic import BaseModel

# ── Init ──────────────────────────────────────────────────────────────────────
PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "nouvia-os")

try:
    log_client = gcloud_logging.Client(project=PROJECT_ID)
    log_client.setup_logging()
except Exception:
    pass

logger = logging.getLogger(__name__)
db     = firestore.Client(project=PROJECT_ID)
app    = FastAPI(title="Delivery Docs Service", version="1.0.0")


# ── Helpers ───────────────────────────────────────────────────────────────────

def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def get_comm_doc(comm_id: str) -> dict:
    snap = db.collection("client_communications").document(comm_id).get()
    if not snap.exists:
        raise HTTPException(status_code=404, detail=f"Document {comm_id} not found")
    return {"id": snap.id, **snap.to_dict()}


def extract_markdown(comm: dict) -> str:
    """Return Markdown string from a client_communications document.
    Handles both storage formats:
      - New: content is a plain Markdown string
      - Legacy: content is {"body": "<markdown>"}
    """
    content = comm.get("content", "")
    if isinstance(content, dict):
        return content.get("body", "")
    return content or ""


# ── Markdown → docx ───────────────────────────────────────────────────────────

def _inline(para, text: str):
    """Add inline-formatted text (bold, italic, code) to a paragraph."""
    tokens = re.split(r'(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)', text)
    for tok in tokens:
        if tok.startswith("**") and tok.endswith("**"):
            para.add_run(tok[2:-2]).bold = True
        elif tok.startswith("*") and tok.endswith("*"):
            para.add_run(tok[1:-1]).italic = True
        elif tok.startswith("`") and tok.endswith("`"):
            run = para.add_run(tok[1:-1])
            run.font.name = "Courier New"
            run.font.size = Pt(10)
        else:
            para.add_run(tok)


def markdown_to_docx_bytes(md_text: str, title: str, client_id: str,
                            version: int = 1) -> bytes:
    doc = Document()

    # ── Document title ────────────────────────────────────────────────────────
    h = doc.add_heading(title, level=0)
    h.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in h.runs:
        run.font.color.rgb = RGBColor(0x00, 0x62, 0xE6)

    # ── Metadata line ─────────────────────────────────────────────────────────
    meta = doc.add_paragraph()
    run  = meta.add_run(
        f"Client: {client_id.upper()}  ·  Version {version}  ·  "
        f"Generated by Nouvia Intelligence Platform"
    )
    run.italic = True
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x94, 0xa3, 0xb8)
    doc.add_paragraph()  # spacer

    # ── Body: line-by-line Markdown parse ─────────────────────────────────────
    list_style_names = [s.name for s in doc.styles]

    for line in md_text.split("\n"):
        stripped = line.strip()

        if stripped.startswith("### "):
            doc.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith(("- ", "* ")):
            bullet_style = "List Bullet" if "List Bullet" in list_style_names else "Normal"
            p = doc.add_paragraph(style=bullet_style)
            _inline(p, stripped[2:])
        elif re.match(r"^\d+\.\s", stripped):
            num_style = "List Number" if "List Number" in list_style_names else "Normal"
            p = doc.add_paragraph(style=num_style)
            _inline(p, re.sub(r"^\d+\.\s", "", stripped))
        elif stripped.startswith("> "):
            p = doc.add_paragraph()
            run = p.add_run(stripped[2:])
            run.italic = True
            run.font.color.rgb = RGBColor(0x64, 0x74, 0x8b)
        elif stripped in ("", "---", "***"):
            doc.add_paragraph()
        else:
            p = doc.add_paragraph()
            _inline(p, stripped)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ── Markdown → PDF ────────────────────────────────────────────────────────────

def markdown_to_pdf_bytes(md_text: str, title: str, client_id: str,
                          version: int = 1) -> bytes:
    """Convert Markdown to PDF using fpdf2 (pure Python, no system deps).
    Uses fpdf2's built-in HTML writer after converting Markdown → HTML.
    """
    html_body = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code"],
    )
    # fpdf2 write_html accepts a subset of HTML; wrap with title/meta block
    full_html = (
        f"<h1>{title}</h1>"
        f"<p><i>Client: {client_id.upper()} &nbsp;|&nbsp; "
        f"Version {version} &nbsp;|&nbsp; Nouvia Intelligence Platform</i></p>"
        f"<hr/>"
        f"{html_body}"
    )

    pdf = FPDF()
    pdf.set_margins(left=20, top=20, right=20)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.write_html(full_html)

    buf = io.BytesIO(pdf.output())
    buf.seek(0)
    return buf.read()


# ── Models ────────────────────────────────────────────────────────────────────

class ExportRequest(BaseModel):
    communication_id: str
    format: str = "docx"   # "docx" | "pdf"


# ── Endpoint: POST /docs/export ───────────────────────────────────────────────

@app.post("/docs/export")
async def export_doc(req: ExportRequest):
    if req.format not in ("docx", "pdf"):
        raise HTTPException(status_code=400, detail="format must be 'docx' or 'pdf'")

    comm    = get_comm_doc(req.communication_id)
    md_text = extract_markdown(comm)

    if not md_text.strip():
        raise HTTPException(status_code=422, detail="Document has no content to export")

    title     = comm.get("title", "Enablement Document")
    client_id = comm.get("client_id", "client")
    version   = comm.get("version", 1)

    # Sanitise filename
    safe = re.sub(r"[^\w\s-]", "", title).strip().replace(" ", "_")[:60]

    if req.format == "docx":
        file_bytes = markdown_to_docx_bytes(md_text, title, client_id, version)
        filename   = f"{safe}_v{version}.docx"
        media_type = (
            "application/vnd.openxmlformats-officedocument"
            ".wordprocessingml.document"
        )
    else:
        file_bytes = markdown_to_pdf_bytes(md_text, title, client_id, version)
        filename   = f"{safe}_v{version}.pdf"
        media_type = "application/pdf"

    logger.info(
        f"export {req.communication_id} as {req.format}: "
        f"{len(file_bytes):,} bytes  version={version}"
    )
    return StreamingResponse(
        io.BytesIO(file_bytes),
        media_type=media_type,
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ── Endpoint: GET /docs/{communication_id} ────────────────────────────────────

@app.get("/docs/{communication_id}")
async def get_doc_meta(communication_id: str):
    """Return document metadata + Markdown content (for AIMS portal rendering)."""
    comm    = get_comm_doc(communication_id)
    md_text = extract_markdown(comm)
    return {
        "id":           comm["id"],
        "title":        comm.get("title", ""),
        "client_id":    comm.get("client_id", ""),
        "doc_type":     comm.get("doc_type", ""),
        "status":       comm.get("status", "draft"),
        "version":      comm.get("version", 1),
        "word_count":   comm.get("word_count", 0),
        "generated_at": comm.get("generated_at", ""),
        "updated_at":   comm.get("updated_at", ""),
        "content":      md_text,
    }


# ── Endpoint: GET /docs/{communication_id}/revisions ─────────────────────────

@app.get("/docs/{communication_id}/revisions")
async def list_revisions(communication_id: str):
    """List all prior revisions for a document (metadata only, no body)."""
    revs = (
        db.collection("client_communications")
        .document(communication_id)
        .collection("revisions")
        .order_by("version", direction=firestore.Query.DESCENDING)
        .get()
    )
    return {
        "communication_id": communication_id,
        "revisions": [
            {
                "version":     d.get("version"),
                "archived_at": d.get("archived_at"),
                "word_count":  d.get("word_count", 0),
            }
            for d in [r.to_dict() for r in revs]
        ],
    }


# ── Endpoint: GET /docs/health ────────────────────────────────────────────────

@app.get("/docs/health")
async def service_health():
    return {
        "service":   "delivery-docs",
        "status":    "healthy",
        "version":   "1.0.0",
        "timestamp": now_iso(),
    }
